# Generated by Django 3.2.7 on 2021-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211001_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='id',
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
