# Generated by Django 3.2.7 on 2021-10-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='down_persons',
        ),
    ]
