# Generated by Django 3.2.7 on 2021-10-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_floor_down_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
